sudo:required
services:
    -docker
    
before_install:
    -docker build -t alexandrecorcia/react-test -f ./client/Dockerfile.dev ./client

script:
   - docker run  -e CI=true alexandrecorcia/react-test npm test

after_success:
    - docker build -t alexandrecorcia/multi-client ./client
    - docker build -t alexandrecorcia/multi-nginx ./nginx
    - docker build -t alexandrecorcia/multi-server ./server
    - docker build -t alexandrecorcia/multi-worker ./worker
#login to the docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#take image and push then to docker hub
- docker push alexandrecorcia/multi-client
- docker push alexandrecorcia/multi-nginx
- docker push alexandrecorcia/multi-server
- docker push alexandrecorcia/multi-worker

    