langage: generic
sudo: required
services:
    -docker
    
before_install:
    -docker build -t 1078aco/react-test -f ./client/Dockerfile.dev ./client

script:
   - docker run  -e CI=true 1078aco/react-test npm test

after_success:
    - docker build -t 1078aco/multi-client ./client
    - docker build -t 1078aco/multi-nginx ./nginx
    - docker build -t 1078aco/multi-server ./server
    - docker build -t 1078aco/multi-worker ./worker
#login to the docker CLI
#- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#take image and push then to docker hub
#- docker push 1078aco/multi-client
#- docker push 1078aco/multi-nginx
#- docker push 1078aco/multi-server
#- docker push 1078aco/multi-worker

    